import "@/assets/css/globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Header } from '@/components/molecules/Header';
import { Sidebar } from '@/components/molecules/Sidebar';
import { Footer } from '@/components/molecules/Footer';
import { PageStepper } from "@/components/molecules/PageStepper";
import { ProfileData as data } from "./config/content";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: `${data.fname} ${data.lname} | Portfolio`,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="wrapper">
          <Header />
          <div className="container flex">
            <Sidebar />
            <main className="content-area">
              <div className="maincontent">{children}</div>
              <PageStepper />
            </main>
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}